FROM node:alpine
RUN npm install --global node-pre-gyp
RUN apk --no-cache add --virtual native-deps \
  g++ gcc libgcc libstdc++ linux-headers autoconf automake make nasm python git && \
  npm install --quiet node-gyp -g

# Create app directory
WORKDIR /usr/src/app/server

COPY ./server/package*.json ./
RUN npm install
RUN npm install bcrypt
RUN npm install sqlite3
COPY . /usr/src/app/

#EXPOSE 3100 9229

CMD ["node","/server/bin/www"]