version: '3.7'
services:
  # pgAdmin-application:
  #   restart: always
  #   image: dpage/pgadmin4
  #   ports:
  #       - "8001:80"
  #   env_file: "debug.env"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  # postgres-application:
  #   restart: always
  #   image: "application/postgres-postgis"
  #   env_file: "debug.env"
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data
  server-application:
    env_file: "debug.env"
    build:
      context: ../../
      dockerfile: ./server/dockerfile
    image: "benedettagiorgi/pulsbs:serverDebug"
    ports:
     - "3100:3100"
     - "9229:9229" #DEBUG
    restart: always
    # depends_on:
    #   - postgres-application
    command: npm start
  client-application:
    env_file: "../../client/client.env"
    tty: true #interation mode
    stdin_open: true #interation mode
    build:
      context: ../../
      dockerfile: ./client/dockerfile
    image: "benedettagiorgi/pulsbs:clientDebug"
    ports:
     - "3000:3000"
    restart: always
    volumes:
    #    - ./client:/usr/src/app/client
         - /usr/src/app/client/node_modules
    depends_on:
      - server-application
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    command: npm start
# volumes:
#   pg-data:
#   pgadmin-data:
