on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get main
      run: git fetch origin main
    - name: Install dependencies server
      run:  npm --prefix ./server install
    - name: Install dependencies client
      run:  npm --prefix ./client install
    - name: Install Jest globally
      run:  sudo npm --prefix ./server install -g jest
    - name: Install jest-sonar-reporter globally
      run:  sudo npm install -g jest-sonar-reporter
    - name: Run Tests Server
      run:  npm --prefix ./server run test
    - name: Run Tests Client
      run:  npm --prefix ./client run test-ci -- --coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
